### ISSUE TITLE
Desorganized

### ISSUE THREAD

**Issue by iTzHuGo** [NunoVz/Exe-PPP#1]
This repo is very disorganised, please take a bit of time to organise it.
![tenor](https://user-images.githubusercontent.com/73546800/108233114-5c458080-713b-11eb-917e-312a888aba8a.gif)

**Comment by NunoVz** [comment]
Paga-me.

https://user-images.githubusercontent.com/76536544/108233984-3a98c900-713c-11eb-8fc5-02a802e0ceca.mp4

**Comment by NunoVz** [comment]
> This repo is very disorganised, please take a bit of time to organise it.
Paga-me.
https://user-images.githubusercontent.com/76536544/108234043-4d130280-713c-11eb-9cdf-bfc72dca4506.mp4

**Comment by NunoVz** [comment]
> This repo is very disorganised, please take a bit of time to organise it.

Paga-me!

https://user-images.githubusercontent.com/76536544/108234209-7c297400-713c-11eb-8289-8432d66c1cbf.mp4
